-- adblock 内置兜底规则：首次启动、离线、订阅还没下载下来时用。
-- 只收最确定的广告/追踪网络与最通用的元素隐藏选择器，宁少勿错。订阅到达后与订阅合并编译。
return [[
! LemurX adblock builtin (ABP syntax)
! ---- 广告网络（第三方）----
||doubleclick.net^
||googlesyndication.com^
||googleadservices.com^
||adservice.google.com^
||adservice.google.com.hk^
||pagead2.googlesyndication.com^
||tpc.googlesyndication.com^
||2mdn.net^$third-party
||adnxs.com^
||adsrvr.org^
||rubiconproject.com^
||pubmatic.com^
||openx.net^
||criteo.com^
||criteo.net^
||taboola.com^
||outbrain.com^
||mgid.com^
||revcontent.com^
||zedo.com^
||adform.net^
||smartadserver.com^
||casalemedia.com^
||indexww.com^
||33across.com^
||bidswitch.net^
||sharethrough.com^
||teads.tv^
||yieldmo.com^
||media.net^
||amazon-adsystem.com^
||moatads.com^
||serving-sys.com^
||advertising.com^
||adcolony.com^
||applovin.com^$third-party
||unityads.unity3d.com^
||inmobi.com^
||chartboost.com^
||vungle.com^
||propellerads.com^
||popads.net^
||popcash.net^
||adsterra.com^
||exoclick.com^
||juicyads.com^
||trafficjunky.net^
||hilltopads.net^
||onclickads.net^
||adskeeper.co.uk^
||adcash.com^
||yllix.com^
||bidvertiser.com^
||adroll.com^
||adtech.de^
||adition.com^
||adscale.de^
||ligatus.com^
||plista.com^
||sovrn.com^
||lijit.com^
||gumgum.com^
||undertone.com^
||conversantmedia.com^
||mediamath.com^
||turn.com^
||rfihub.com^
||simpli.fi^
||tremorhub.com^
||spotxchange.com^
||spotx.tv^
||innovid.com^
||springserve.com^
||freewheel.tv^$third-party
||fwmrm.net^
! ---- 追踪 / 统计 ----
||scorecardresearch.com^
||quantserve.com^
||quantcount.com^
||bluekai.com^
||krxd.net^
||exelator.com^
||demdex.net^
||everesttech.net^
||omtrdc.net^
||chartbeat.com^
||chartbeat.net^
||crwdcntrl.net^
||agkn.com^
||rlcdn.com^
||tapad.com^
||adsymptotic.com^
||mookie1.com^
||eyeota.net^
||ml314.com^
||branch.io^$third-party
||doubleverify.com^
||adsafeprotected.com^
||google-analytics.com^$third-party
||googletagservices.com^$third-party
||hotjar.com^$third-party
||mouseflow.com^$third-party
||fullstory.com^$third-party
||clarity.ms^$third-party
||facebook.net/en_US/fbevents.js
||connect.facebook.net/signals/
! ---- 中文站常见 ----
||cpro.baidu.com^
||pos.baidu.com^
||cbjs.baidu.com^
||cpro.baidustatic.com^
||eclick.baidu.com^
||hm.baidu.com^$third-party
||tanx.com^
||alimama.com^$third-party
||mmstat.com^$third-party
||cnzz.com^$third-party
||51.la^$third-party
||miaozhen.com^
||admaster.com.cn^
||mediav.com^
||irs01.com^
||irs01.net^
||ipinyou.com^
||yoyi.com.cn^
||adsage.com^
||adsage.cn^
||allyes.com^
||adchina.com^
||dsp.360.cn^
||union.360.cn^
||show.g.mediav.com^
||googleads.g.doubleclick.net^
||wrating.com^
||gridsumdissector.com^
||umeng.com^$third-party
||umengcloud.com^$third-party
||getui.com^$third-party
||jpush.cn^$third-party
||sogou.com/adsrc^
||adsame.com^
||eqxiu.com/track
||fastapi.net^
! ---- 通用元素隐藏 ----
##.adsbygoogle
##ins.adsbygoogle
##div[id^="div-gpt-ad"]
##div[id^="google_ads_iframe"]
##.google-auto-placed
##.ad-banner
##.ad-container
##.ad-wrapper
##.ad-slot
##.ad-placeholder
##.adsbox
##.ad_wrap
##.ad-leaderboard
##.ad-sidebar
##.ad-footer
##.ad-header
##.advertisement
##.advertising
##.sponsored-content
##.sponsored-post
##.taboola
##.OUTBRAIN
##.trc_related_container
##[id^="taboola-"]
##iframe[src*="doubleclick.net"]
##iframe[src*="googlesyndication.com"]
##a[href*="cpro.baidu.com"]
##a[href*="pos.baidu.com"]
##div[id^="BAIDU_SSP"]
##div[id^="BAIDU_DUP"]
##div[class^="baidu-ad"]
##.ec_wise_ad
##div[id^="cpro_"]
##div[id^="_ad_"]
##.ad-popup
##.ad-float
##.floatad
##.float-ad
##.fixed-ad
##.popup-ad
##.gg-box
##.guanggao
##.ggbox
##.adbox
##.ad-list
##.ad_list
##div[class*="_ad_"][class*="banner"]
]]
