-- LemurX · luakit-compatible library · window
-- Copyright (c) 2026 LemurX. All rights reserved.
-- Independent implementation of the luakit "window" module API. No luakit code is used.
--
-- 浏览器外壳：为每个窗口搭出控件树
--   window → vbox(layout) → [tablist] → paned(notebook) → menu → statusbar(l/r hbox in eventbox) → input bar(prompt + entry)
-- 并提供 w:new_tab / close_tab / close_win / goto_tab / notify / run_cmd 等方法，
-- 以及 window.new / window.bywidget / window.methods / window.indexes / window.init_funcs /
-- window.ancestor / window.current。模式(set_mode)与按键绑定表由 modes.lua 填充，
-- 这里只给出最小的默认实现，保证 window 单独 require 时也能工作。

local lousy = require("lousy")
local util = lousy.util
local join = util.table.join
local escape = util.escape

local _M = {}
lousy.signal.setup(_M, true)

-- ---------------------------------------------------------------------------
-- settings 是 C 组的模块：可能还没就位，全部通过守卫访问
-- ---------------------------------------------------------------------------
local settings = package.loaded["settings"]
if not settings then
    local ok, mod = pcall(require, "settings")
    if ok and type(mod) == "table" then settings = mod end
end

local function get_setting(key, default)
    if settings and settings.get_setting then
        local ok, v = pcall(settings.get_setting, key)
        if ok and v ~= nil then return v end
    end
    return default
end

if settings and settings.register_settings then
    local ok, err = pcall(settings.register_settings, {
        ["window.home_page"] = {
            type = "string", default = "https://duckduckgo.com/",
            desc = "URI opened by gH / <Control-t> and by an empty new window.",
        },
        ["window.new_tab_page"] = {
            type = "string", default = "about:blank",
            desc = "URI loaded into a tab that was opened without an address.",
        },
        ["window.scroll_step"] = {
            type = "number", default = 40, min = 1,
            desc = "Pixels moved by one step of j / k / h / l.",
        },
        ["window.zoom_step"] = {
            type = "number", default = 0.1, min = 0.01,
            desc = "Zoom factor delta applied by + / - (1 = 100%).",
        },
        ["window.search_engines"] = {
            type = "string:", default = {
                duckduckgo = "https://duckduckgo.com/?q=%s",
                google = "https://www.google.com/search?q=%s",
                bing = "https://www.bing.com/search?q=%s",
                wikipedia = "https://en.wikipedia.org/wiki/Special:Search?search=%s",
                github = "https://github.com/search?q=%s",
            },
            desc = "Keyword → search URL map; %s is replaced by the encoded query.",
        },
        ["window.default_search_engine"] = {
            type = "string", default = "duckduckgo",
            desc = "Engine used when the typed text is not a URI and starts with no known keyword.",
        },
        ["window.close_with_last_tab"] = {
            type = "boolean", default = false,
            desc = "Close the window when its last tab is closed instead of opening a blank tab.",
        },
        ["window.max_title_len"] = {
            type = "number", default = 80, min = 8,
            desc = "Longest window title before it is cut off.",
        },
        ["window.act_on_synthetic_keys"] = {
            type = "boolean", default = false,
            desc = "Whether keys generated by keysym.send / send_key also trigger key bindings.",
        },
        ["window.check_filepath"] = {
            type = "boolean", default = true,
            desc = "Treat typed text that names an existing local file as a file:// URI.",
        },
        ["window.new_window_size"] = {
            type = "string", default = "800x600",
            desc = "Default size (WxH) requested for new windows; mostly ignored on Android.",
        },
        ["window.reuse_new_tab_pages"] = {
            type = "boolean", default = false,
            desc = "Reuse an existing blank new-tab page instead of opening another tab.",
        },
    })
    if not ok then msg.warn("window: settings registration failed: %s", tostring(err)) end
end

-- ---------------------------------------------------------------------------
-- 主题：lousy.theme.get() 可能尚未初始化，给一份兜底
-- ---------------------------------------------------------------------------
local fallback_theme = setmetatable({
    font = "sans 10", fg = "#e6e6e6", bg = "#1b1b1b",
    ibar_fg = "#e6e6e6", ibar_bg = "#1b1b1b", ibar_font = "monospace 10",
    sbar_fg = "#e6e6e6", sbar_bg = "#1b1b1b", sbar_font = "monospace 10",
    notif_fg = "#ffffff", notif_bg = "#2b5797",
    warning_fg = "#1b1b1b", warning_bg = "#f0c040",
    error_fg = "#ffffff", error_bg = "#a02020",
    menu_fg = "#e6e6e6", menu_bg = "#252525",
}, { __index = function(t, k)
    if type(k) == "string" then
        if k:match("_fg$") then return rawget(t, "fg") end
        if k:match("_bg$") then return rawget(t, "bg") end
        if k:match("_font$") then return rawget(t, "font") end
    end
    return nil
end })

local function theme()
    if lousy.theme and lousy.theme.get then
        local ok, t = pcall(lousy.theme.get)
        if ok and type(t) == "table" and next(t) ~= nil then return t end
    end
    return fallback_theme
end
_M.theme = theme

-- ---------------------------------------------------------------------------
-- 模块级表
-- ---------------------------------------------------------------------------
_M.bywidget = setmetatable({}, { __mode = "k" })
_M.methods = {}
_M.indexes = {}
_M.init_funcs = {}
_M.close_win_when_empty = true
_M.quit_when_no_windows = true
_M.default_sbar_widgets = {
    l = { "uri", "hist", "progress" },
    r = { "buf", "ssl", "tabi", "scroll" },
}
_M.last_active = nil

local methods = _M.methods

-- 延迟取其他模块，避免顶层循环 require
local function webview_mod()
    return package.loaded["webview"] or require("webview")
end
local function modes_mod()
    return package.loaded["modes"]
end
local function taborder_mod()
    return package.loaded["taborder"]
end

local function is_widget(v) return type(v) == "widget" end
local function is_view(v) return is_widget(v) and v.type == "webview" end

-- 窗口表的元表：先查 window.methods，再依次问 window.indexes 里的索引函数
local window_mt = {
    __index = function(w, k)
        local m = methods[k]
        if m ~= nil then return m end
        for _, fn in ipairs(_M.indexes) do
            local v = fn(w, k)
            if v ~= nil then return v end
        end
        return nil
    end,
}

-- ---------------------------------------------------------------------------
-- 查找
-- ---------------------------------------------------------------------------
function _M.ancestor(widget)
    if not is_widget(widget) then return nil end
    local cur, guard = widget, 0
    while cur and guard < 64 do
        if cur.type == "window" then return _M.bywidget[cur] end
        local ok, parent = pcall(function() return cur.parent end)
        if not ok then break end
        cur = parent
        guard = guard + 1
    end
    -- 兜底：按 notebook 成员关系找
    if widget.type == "webview" then
        for _, w in pairs(_M.bywidget) do
            if w.tabs and w.tabs.is_alive and w.tabs:indexof(widget) then return w end
        end
    end
    return nil
end

function _M.current()
    local la = _M.last_active
    if la and la.win and la.win.is_alive then return la end
    for _, win in ipairs(luakit.windows) do
        local w = _M.bywidget[win]
        if w then return w end
    end
    for _, w in pairs(_M.bywidget) do return w end
    return nil
end

-- ---------------------------------------------------------------------------
-- 控件树
-- ---------------------------------------------------------------------------
local function make_bar_side()
    local side = { layout = widget{ type = "hbox" }, ebox = widget{ type = "eventbox" } }
    side.ebox.child = side.layout
    return side
end

local function make_tablist(w)
    if not (lousy.widget and lousy.widget.tablist) then return nil end
    local ok, tl = pcall(lousy.widget.tablist, w, { orientation = "horizontal", notebook = w.tabs })
    if not ok or type(tl) ~= "table" then
        ok, tl = pcall(lousy.widget.tablist, w.tabs, "horizontal")
    end
    if ok and type(tl) == "table" and tl.widget then return tl end
    msg.verbose("window: tablist widget unavailable (%s)", tostring(tl))
    return nil
end

local function make_menu(w)
    if not (lousy.widget and lousy.widget.menu) then return nil end
    local ok, m = pcall(lousy.widget.menu, w)
    if ok and type(m) == "table" and m.widget then return m end
    msg.verbose("window: menu widget unavailable (%s)", tostring(m))
    return nil
end

function _M.build(w)
    local th = theme()
    w.win = widget{ type = "window" }
    w.layout = widget{ type = "vbox" }
    w.win.child = w.layout

    -- 标签栏 + 页面区域（paned 让 vertical_tabs 之类的模块能把标签栏挪到左侧）
    w.tabs = widget{ type = "notebook" }
    w.tabs.show_tabs = false
    w.tabs.show_border = false
    w.paned = widget{ type = "hpaned" }
    w.paned:pack2(w.tabs, { resize = true, shrink = true })

    w.tablist = make_tablist(w)
    if w.tablist then
        w.layout:pack(w.tablist.widget)
        if w.tablist.add_signal then
            w.tablist:add_signal("tab-clicked", function(_, idx, mods, but)
                if but == 2 then
                    local view = w.tabs:atindex(idx)
                    if view then w:close_tab(view) end
                else
                    w.tabs:switch(idx)
                end
                return true
            end)
        end
    end
    w.layout:pack(w.paned, { expand = true, fill = true })

    -- 菜单（补全、undolist、tabhistory 等模式共用）
    w.menu = make_menu(w)
    if w.menu then
        w.layout:pack(w.menu.widget)
        if w.menu.hide then w.menu:hide() end
    end

    -- 状态栏
    w.sbar = { layout = widget{ type = "hbox" }, ebox = widget{ type = "eventbox" }, hidden = false }
    w.sbar.l = make_bar_side()
    w.sbar.r = make_bar_side()
    w.sbar.layout:pack(w.sbar.l.ebox, { expand = true, fill = true })
    w.sbar.layout:pack(w.sbar.r.ebox)
    w.sbar.ebox.child = w.sbar.layout
    w.sbar.ebox.bg = th.sbar_bg
    w.layout:pack(w.sbar.ebox)

    -- 输入栏
    w.ibar = {
        layout = widget{ type = "hbox" },
        ebox = widget{ type = "eventbox" },
        prompt = widget{ type = "label" },
        input = widget{ type = "entry" },
    }
    w.ibar.prompt.font = th.ibar_font
    w.ibar.input.font = th.ibar_font
    w.ibar.input.show_frame = false
    w.ibar.layout:pack(w.ibar.prompt)
    w.ibar.layout:pack(w.ibar.input, { expand = true, fill = true })
    w.ibar.ebox.child = w.ibar.layout
    w.ibar.ebox.bg = th.ibar_bg
    w.layout:pack(w.ibar.ebox)
    w.ibar.prompt:hide()
    w.ibar.input:hide()

    w.buffer = nil
    w.binds = {}
    w.closed_tabs = w.closed_tabs or {}

    _M.emit_signal("build", w)

    -- rc.lua 没有自己往状态栏塞控件时，放一套默认的
    for side, names in pairs(_M.default_sbar_widgets) do
        local bar = w.sbar[side]
        if bar and #bar.layout.children == 0 and lousy.widget then
            for _, name in ipairs(names) do
                local factory = lousy.widget[name]
                if type(factory) == "function" or (type(factory) == "table" and getmetatable(factory)) then
                    local ok, wd = pcall(factory, w)
                    if ok and is_widget(wd) then
                        bar.layout:pack(wd)
                        bar[name] = wd
                    elseif ok and type(wd) == "table" and is_widget(wd.widget) then
                        bar.layout:pack(wd.widget)
                        bar[name] = wd.widget
                    else
                        msg.verbose("window: statusbar widget %s unavailable: %s", name, tostring(wd))
                    end
                end
            end
        end
    end
end

-- ---------------------------------------------------------------------------
-- 信号接线
-- ---------------------------------------------------------------------------
local function current_mode_table(w)
    local modes = modes_mod()
    if modes and modes.get_mode then return modes.get_mode(w.mode or "normal") end
    return nil
end

local function wire(w)
    -- 按键：window 控件先拿到，吃掉则返回 true
    w.win:add_signal("key-press", function(_, mods, key, synthetic)
        if synthetic and not get_setting("window.act_on_synthetic_keys", false) then return end
        _M.last_active = w
        if w:emit_signal("key-press", mods, key) == true then return true end
        return w:hit(mods, key)
    end)

    w.win:add_signal("delete-event", function()
        w:close_win()
        return true
    end)

    w.win:add_signal("destroy", function()
        _M.bywidget[w.win] = nil
        if _M.last_active == w then _M.last_active = nil end
        w:emit_signal("destroy")
    end)

    w.win:add_signal("focus", function() _M.last_active = w end)

    -- 标签切换
    w.tabs:add_signal("switch-page", function(_, view, idx)
        local prev = w.view
        w.view = view
        if w.built and w.mode and w.mode ~= "normal" and w.mode ~= "insert" then w:set_mode() end
        w:update_win_title()
        if view and view.is_alive then pcall(view.emit_signal, view, "switched-page") end
        w:emit_signal("switched-page", view, prev)
    end)
    w.tabs:add_signal("page-added", function() w:emit_signal("tab-count-changed") end)
    w.tabs:add_signal("page-removed", function(_, view)
        if w.view == view then w.view = nil end
        w:emit_signal("tab-count-changed")
    end)
    w.tabs:add_signal("page-reordered", function(_, view, idx) w:emit_signal("tab-reordered", view, idx) end)

    -- 输入栏：模式表里的 changed / activate 处理器
    w.ibar.input:add_signal("changed", function()
        local m = current_mode_table(w)
        if m and m.changed then m.changed(w, w.ibar.input.text or "") end
    end)
    w.ibar.input:add_signal("activate", function()
        local m = current_mode_table(w)
        if m and m.activate then m.activate(w, w.ibar.input.text or "") end
    end)
end

-- ---------------------------------------------------------------------------
-- 方法
-- ---------------------------------------------------------------------------
methods.get_current = function(w) return w.view end
methods.tab_count = function(w) return w.tabs:count() end
methods.update_buf = function() end          -- lousy.widget.buf 会覆盖
methods.set_binds = function(w, binds) w.binds = binds or {} end

methods.update_binds = function(w, mode_name)
    local modes = modes_mod()
    if not (modes and modes.get_mode) then w.binds = {} return end
    local m = modes.get_mode(mode_name or w.mode or "normal")
    local out = {}
    for _, b in ipairs(m and m.binds or {}) do out[#out + 1] = b end
    if not (m and m.passthrough) then
        local all = modes.get_mode("all")
        for _, b in ipairs(all and all.binds or {}) do out[#out + 1] = b end
    end
    w.binds = out
end

-- 默认模式实现（modes.lua 会替换成完整版）
methods.set_mode = function(w, name, ...)
    name = name or "normal"
    local old = w.mode
    w.mode = name
    w:update_binds(name)
    w:emit_signal("mode-changed", name, ...)
    if old ~= name then w:emit_signal("mode-entered", name) end
end
methods.is_mode = function(w, name) return w.mode == name end

-- 计数前缀 + 缓冲区 + lousy.bind.hit
methods.hit = function(w, mods, key, opts)
    opts = opts or {}
    local m = current_mode_table(w)
    local enable_buffer = opts.enable_buffer
    if enable_buffer == nil then enable_buffer = (m and m.enable_buffer) or false end
    local buffer = opts.buffer or w.buffer or ""
    local count, rest = buffer:match("^(%d+)(.*)$")
    local plain = (#mods == 0)

    if enable_buffer and plain and key:match("^%d$") and
       ((buffer == "" and key ~= "0") or (count and rest == "")) then
        w.buffer = buffer .. key
        w:update_buf()
        return true
    end

    local args = join(opts, { enable_buffer = enable_buffer, buffer = count and rest or buffer })
    if count then args.count = tonumber(count) end
    local caught, newbuf = lousy.bind.hit(w, w.binds or {}, mods, key, args)
    newbuf = newbuf or ""
    if not caught then newbuf = "" end
    if caught and newbuf ~= "" and count then newbuf = count .. newbuf end
    w.buffer = (newbuf ~= "") and newbuf or nil
    w:update_buf()
    return caught and true or false
end

methods.match_cmd = function(w, text, opts)
    local modes = modes_mod()
    local binds = {}
    if modes and modes.get_mode then
        local cm = modes.get_mode("command")
        binds = cm and cm.binds or {}
    end
    return lousy.bind.match_cmd(w, binds, text, opts or {})
end

methods.run_cmd = function(w, text, opts)
    text = tostring(text or "")
    text = text:gsub("^%s*:", ""):gsub("^%s+", ""):gsub("%s+$", "")
    if text == "" then return false end
    w:emit_signal("run-cmd", text)
    local name, rest = text:match("^(%S+)(.*)$")
    local o = join(opts or {}, {})
    if name:sub(-1) == "!" then
        o.bang = true
        text = name:sub(1, -2) .. rest
        name = name:sub(1, -2)
    end
    local ok, matched = xpcall(function() return w:match_cmd(text, o) end, debug.traceback)
    if not ok then
        msg.error("command %q failed: %s", name, tostring(matched))
        w:error(("command %s failed: %s"):format(name, tostring(matched):match("^[^\n]*")))
        return false
    end
    if not matched then
        w:error(("no such command: %s"):format(name))
        return false
    end
    return true
end

methods.enter_cmd = function(w, cmd, opts)
    opts = opts or {}
    w:set_mode("command")
    w:set_input(cmd or ":", opts)
end

-- 输入栏
methods.set_prompt = function(w, text, opts)
    opts = opts or {}
    local p = w.ibar.prompt
    w.ibar.prompt_text = text
    if text == nil or text == "" then
        p.text = ""
        p:hide()
        return
    end
    local th = theme()
    if opts.fg then p.fg = opts.fg end
    if opts.bg then p.bg = opts.bg; w.ibar.ebox.bg = opts.bg end
    if not opts.markup then text = escape(text) end
    p.text = text
    p:show()
end

methods.set_input = function(w, text, opts)
    opts = opts or {}
    local i = w.ibar.input
    if text == nil or (text == "" and not opts.show) then
        i.text = ""
        i:hide()
        return
    end
    i:show()
    if opts.fg then i.fg = opts.fg end
    if opts.bg then i.bg = opts.bg end
    i.text = text
    local pos = opts.pos
    if pos == nil or pos < 0 then pos = utf8.len(text) or #text end
    i.position = pos
    i:focus()
end

methods.set_ibar_theme = function(w, name)
    local th = theme()
    local fg, bg = th.ibar_fg, th.ibar_bg
    if name then
        fg = th[name .. "_fg"] or fg
        bg = th[name .. "_bg"] or bg
    end
    w.ibar.ebox.bg = bg
    w.ibar.prompt.fg = fg
    w.ibar.prompt.bg = bg
    w.ibar.input.fg = fg
    w.ibar.input.bg = bg
end

local function message(level, w, text, set_mode)
    text = tostring(text)
    if set_mode ~= false then w:set_mode() end
    local th = theme()
    w:set_prompt(text, { fg = th[level .. "_fg"], bg = th[level .. "_bg"] })
    w.ibar.last_message = { level = level, text = text }
end
methods.notify = function(w, text, set_mode) message("notif", w, text, set_mode) msg.info("%s", tostring(text)) end
methods.warning = function(w, text, set_mode) message("warning", w, text, set_mode) msg.warn("%s", tostring(text)) end
methods.error = function(w, text, set_mode) message("error", w, text, set_mode) msg.error("%s", tostring(text)) end

-- 状态栏显隐
methods.hide_sbar = function(w) w.sbar.ebox:hide() w.sbar.hidden = true end
methods.show_sbar = function(w) w.sbar.ebox:show() w.sbar.hidden = false end
methods.toggle_sbar = function(w) if w.sbar.hidden then w:show_sbar() else w:hide_sbar() end end
methods.set_status_visible = function(w, on) if on then w:show_sbar() else w:hide_sbar() end end
methods.set_ibar_visible = function(w, on) if on then w.ibar.ebox:show() else w.ibar.ebox:hide() end end

methods.show_menu = function(w, rows)
    if not w.menu then return end
    if rows then w.menu:build(rows) end
    w.menu:show()
end
methods.hide_menu = function(w)
    if w.menu and w.menu.hide then w.menu:hide() end
end

-- 标题
methods.get_tab_title = function(w, view)
    view = view or w.view
    if not (view and view.is_alive) then return "" end
    local title = view.title
    if title == nil or title == "" then title = view.uri end
    if title == nil or title == "" or title == "about:blank" then title = "(no title)" end
    return title
end

methods.update_win_title = function(w)
    if not (w.win and w.win.is_alive) then return end
    local view = w.view
    local title = "LemurX"
    if view and view.is_alive then
        title = w:get_tab_title(view)
        pcall(function() w.tabs:set_title(view, title) end)
    end
    local max = tonumber(get_setting("window.max_title_len", 80)) or 80
    if utf8.len(title) and utf8.len(title) > max then
        title = title:sub(1, utf8.offset(title, max + 1) - 1) .. "…"
    end
    w.win.title = title .. " — luakit"
end

-- 标签管理
methods.new_tab = function(w, arg, opts)
    if type(opts) == "boolean" then opts = { switch = opts } end
    opts = opts or {}
    local switch = opts.switch ~= false
    local view
    if is_view(arg) then
        view = arg
        local owner = _M.ancestor(view)
        if owner and owner ~= w then owner:detach_tab(view) end
    else
        view = webview_mod().new({ private = opts.private or w.private or false })
    end

    local order = opts.order
    local taborder = taborder_mod()
    if not order and taborder then
        order = switch and taborder.default or taborder.default_bg
    end
    local idx = -1
    if type(order) == "function" then
        local ok, i = pcall(order, w, view)
        if ok and type(i) == "number" then idx = i end
    end
    local count = w.tabs:count()
    if idx < 1 or idx > count + 1 then idx = count + 1 end
    local pos = w.tabs:insert(idx, view) or idx
    w:emit_signal("attach-tab", view)
    w:emit_signal("new-tab", view)
    if switch then w.tabs:switch(pos) end
    if not is_view(arg) then
        local target = arg
        if target == nil or target == "" then target = get_setting("window.new_tab_page", "about:blank") end
        webview_mod().set_location(view, target)
    end
    if w.tabs:count() == 1 and not w.view then w.tabs:switch(1) end
    return view
end

methods.attach_tab = function(w, view, opts) return w:new_tab(view, opts) end

methods.detach_tab = function(w, view)
    view = view or w.view
    if not is_view(view) then return end
    local idx = w.tabs:indexof(view)
    if not idx then return end
    w:emit_signal("detach-tab", view)
    w.tabs:remove(view)
    if w.view == view then w.view = nil end
    local count = w.tabs:count()
    if count > 0 then
        w.tabs:switch(math.min(idx, count))
    elseif w.built then
        if _M.close_win_when_empty then w:close_win(true) end
    end
    return view
end

methods.close_tab = function(w, view, blank_last)
    view = view or w.view
    if not is_view(view) then return end
    local idx = w.tabs:indexof(view)
    if not idx then return end
    local last = (w.tabs:count() == 1)
    w:emit_signal("close-tab", view)
    if last then
        local close_win = get_setting("window.close_with_last_tab", false) and not blank_last
        if close_win then
            w.closing_last_tab = true
        else
            w:new_tab(get_setting("window.new_tab_page", "about:blank"), { switch = true, order = function() return 1 end })
            idx = w.tabs:indexof(view) or idx
        end
    end
    w:emit_signal("detach-tab", view)
    w.tabs:remove(view)
    if w.view == view then w.view = nil end
    pcall(view.destroy, view)
    local count = w.tabs:count()
    if count > 0 then
        w.tabs:switch(math.min(idx, count))
    end
    w:emit_signal("tab-count-changed")
    if w.closing_last_tab then
        w.closing_last_tab = nil
        w:close_win()
    end
end

methods.each_tab = function(w, fn)
    for i = 1, w.tabs:count() do
        local v = w.tabs:atindex(i)
        if v then fn(v, i) end
    end
end

methods.goto_tab = function(w, n)
    local count = w.tabs:count()
    if count == 0 then return end
    n = tonumber(n) or 1
    if n < 0 then n = count + n + 1 end
    if n < 1 then n = 1 end
    if n > count then n = count end
    w.tabs:switch(n)
end

methods.next_tab = function(w, n)
    local count = w.tabs:count()
    if count == 0 then return end
    n = tonumber(n) or 1
    w.tabs:switch(((w.tabs:current() - 1 + n) % count) + 1)
end

methods.prev_tab = function(w, n)
    local count = w.tabs:count()
    if count == 0 then return end
    n = tonumber(n) or 1
    w.tabs:switch(((w.tabs:current() - 1 - n) % count) + 1)
end

methods.move_tab = function(w, offset)
    local view = w.view
    if not view then return end
    local count = w.tabs:count()
    local idx = w.tabs:indexof(view) or 1
    local target = ((idx - 1 + offset) % count) + 1
    w.tabs:reorder(view, target)
end

-- 导航
methods.navigate = function(w, uri, view)
    view = view or w.view
    if is_view(view) then
        webview_mod().set_location(view, uri)
        return view
    end
    return w:new_tab(uri)
end

methods.search_open = function(w, text)
    return webview_mod().resolve_location(text)
end

methods.new_window = function(w, uri)
    local args = {}
    if uri ~= nil then args[1] = uri end
    return _M.new(args)
end

-- 关窗
methods.can_quit = function(w)
    return w:emit_signal("can-close") ~= false
end

methods.close_win = function(w, force)
    if not (w.win and w.win.is_alive) then return true end
    if not force and w:emit_signal("can-close") == false then return false end
    w:emit_signal("close")
    -- 先把页面摘掉再销毁，避免 notebook 级联时重复回调
    local views = {}
    w:each_tab(function(v) views[#views + 1] = v end)
    for _, v in ipairs(views) do
        pcall(function() w.tabs:remove(v) end)
        pcall(v.destroy, v)
    end
    w.view = nil
    w.win:destroy()
    if _M.quit_when_no_windows and #luakit.windows == 0 then
        luakit.quit()
    end
    return true
end

-- ---------------------------------------------------------------------------
-- 构造
-- ---------------------------------------------------------------------------
function _M.new(args)
    args = args or {}
    if type(args) == "string" then args = { args } end
    local w = setmetatable({ private = args.private == true }, window_mt)
    lousy.signal.setup(w)
    w.closed_tabs = {}
    w.search_state = {}
    _M.build(w)
    _M.bywidget[w.win] = w
    wire(w)
    _M.last_active = w

    _M.emit_signal("init", w)
    for k, fn in pairs(_M.init_funcs) do
        if type(fn) == "function" then
            local ok, err = xpcall(fn, debug.traceback, w)
            if not ok then msg.error("window.init_funcs[%s]: %s", tostring(k), tostring(err)) end
        end
    end

    w:set_mode()
    w.built = true

    local size = tostring(get_setting("window.new_window_size", "800x600"))
    local sw, sh = size:match("^(%d+)x(%d+)$")
    if sw and w.win.set_default_size then pcall(w.win.set_default_size, w.win, tonumber(sw), tonumber(sh)) end

    local n = 0
    for _, a in ipairs(args) do
        n = n + 1
        w:new_tab(a, { switch = (n == 1) })
    end
    if n == 0 then
        w:new_tab(get_setting("window.home_page", "about:blank"), { switch = true })
    end
    if args.current and w.tabs:count() >= args.current then w.tabs:switch(args.current) end

    w.win:show()
    w:update_win_title()
    return w
end

return _M
