-- wappalyzer/techs · 技术指纹库（手工精选，Wappalyzer 数据格式的子集）
--
-- 每条：
--   name      名称                   cat      分类（见 CATS）
--   js        window 上的全局变量名（页面里 typeof !== 'undefined'），可带 "a.b.c"
--   scripts   <script src> 里的 Lua 模式（不区分大小写）
--   html      文档 HTML 片段里的 Lua 模式（只看前 200KB）
--   meta      { name = 模式 }  <meta name=...content=...>
--   headers   { header = 模式 } 响应头（小写名）
--   cookies   Cookie 名模式
--   dom       CSS 选择器（页面里 querySelector 命中）
--   url       页面 URL 模式
--   version   { js = "全局变量", re = "从 UA/脚本 URL 里取版本的模式" }（可选）
--   implies   命中后顺带认定的技术
local M = {}

M.CATS = {
    cms = "CMS", framework = "Web 框架", js = "JS 框架 / 库", ui = "UI 框架", ecommerce = "电商",
    analytics = "统计 / 分析", ads = "广告", tag = "标签管理", cdn = "CDN", server = "服务器", lang = "编程语言",
    hosting = "托管 / PaaS", ssg = "静态站生成", blog = "博客", forum = "论坛", wiki = "Wiki", lms = "在线课程",
    payment = "支付", chat = "客服 / 聊天", captcha = "验证码", font = "字体", map = "地图", video = "视频播放器",
    security = "安全", search = "站内搜索", marketing = "营销自动化", pwa = "PWA / 性能", ab = "A/B 测试",
    misc = "其他",
}

M.TECHS = {
    -- ===== JS 框架 =====
    { name = "React", cat = "js", js = { "React", "__REACT_DEVTOOLS_GLOBAL_HOOK__" }, dom = { "[data-reactroot]", "[data-reactid]", "#root>*" }, html = { "data%-reactroot", "__reactContainer", "_reactRootContainer" }, version = { js = "React.version" } },
    { name = "Next.js", cat = "framework", js = { "__NEXT_DATA__", "next" }, scripts = { "/_next/static/" }, headers = { ["x-powered-by"] = "Next%.js" }, implies = { "React", "Node.js", "webpack" }, version = { js = "next.version" } },
    { name = "Vue.js", cat = "js", js = { "Vue", "__VUE__", "__VUE_DEVTOOLS_GLOBAL_HOOK__" }, dom = { "[data-v-app]", "[data-server-rendered]" }, html = { "data%-v%-[0-9a-f]{8}" }, version = { js = "Vue.version" } },
    { name = "Nuxt.js", cat = "framework", js = { "__NUXT__", "$nuxt" }, scripts = { "/_nuxt/" }, dom = { "#__nuxt" }, implies = { "Vue.js", "Node.js" } },
    { name = "Angular", cat = "js", js = { "ng", "getAllAngularRootElements" }, dom = { "[ng-version]", "app-root" }, version = { attr = "ng-version" } },
    { name = "AngularJS", cat = "js", js = { "angular" }, dom = { "[ng-app]", "[ng-controller]", ".ng-scope" }, version = { js = "angular.version.full" } },
    { name = "Svelte", cat = "js", dom = { "[class*='svelte-']" }, html = { "svelte%-[0-9a-z]+" } },
    { name = "SvelteKit", cat = "framework", scripts = { "/_app/immutable/" }, js = { "__sveltekit" }, implies = { "Svelte" } },
    { name = "Preact", cat = "js", js = { "preact", "__PREACT_DEVTOOLS__" } },
    { name = "Solid", cat = "js", js = { "_$HY", "Solid" } },
    { name = "Astro", cat = "ssg", dom = { "astro-island", "[data-astro-cid]" }, meta = { generator = "Astro" }, scripts = { "/_astro/" } },
    { name = "Remix", cat = "framework", js = { "__remixContext", "__remixManifest" }, implies = { "React" } },
    { name = "Gatsby", cat = "ssg", js = { "___gatsby" }, dom = { "#___gatsby" }, meta = { generator = "Gatsby" }, implies = { "React" } },
    { name = "Ember.js", cat = "js", js = { "Ember", "Em" }, dom = { ".ember-view", "#ember-basic-dropdown-wormhole" } },
    { name = "Backbone.js", cat = "js", js = { "Backbone" }, version = { js = "Backbone.VERSION" } },
    { name = "jQuery", cat = "js", js = { "jQuery" }, scripts = { "jquery[%.%-]" }, version = { js = "jQuery.fn.jquery" } },
    { name = "jQuery UI", cat = "js", js = { "jQuery.ui" }, scripts = { "jquery%-ui" }, implies = { "jQuery" } },
    { name = "jQuery Mobile", cat = "js", js = { "jQuery.mobile" }, implies = { "jQuery" } },
    { name = "Lodash", cat = "js", js = { "_.chunk", "_.VERSION" }, version = { js = "_.VERSION" } },
    { name = "Underscore.js", cat = "js", js = { "_.templateSettings" } },
    { name = "Moment.js", cat = "js", js = { "moment" }, version = { js = "moment.version" } },
    { name = "Day.js", cat = "js", js = { "dayjs" } },
    { name = "Axios", cat = "js", js = { "axios" } },
    { name = "RxJS", cat = "js", js = { "rxjs", "Rx" } },
    { name = "Redux", cat = "js", js = { "__REDUX_DEVTOOLS_EXTENSION__", "Redux" } },
    { name = "MobX", cat = "js", js = { "__mobxGlobals", "__mobxInstanceCount" } },
    { name = "Alpine.js", cat = "js", js = { "Alpine" }, dom = { "[x-data]" } },
    { name = "htmx", cat = "js", js = { "htmx" }, dom = { "[hx-get]", "[hx-post]" } },
    { name = "Stimulus", cat = "js", js = { "Stimulus" }, dom = { "[data-controller]" } },
    { name = "Hotwire Turbo", cat = "js", js = { "Turbo" }, dom = { "turbo-frame" }, meta = { ["turbo-cache-control"] = "." } },
    { name = "Three.js", cat = "js", js = { "THREE" }, version = { js = "THREE.REVISION" } },
    { name = "D3", cat = "js", js = { "d3" }, version = { js = "d3.version" } },
    { name = "ECharts", cat = "js", js = { "echarts" }, version = { js = "echarts.version" } },
    { name = "Chart.js", cat = "js", js = { "Chart" }, version = { js = "Chart.version" } },
    { name = "Highcharts", cat = "js", js = { "Highcharts" }, version = { js = "Highcharts.version" } },
    { name = "GSAP", cat = "js", js = { "gsap", "TweenMax" }, version = { js = "gsap.version" } },
    { name = "Swiper", cat = "js", js = { "Swiper" }, dom = { ".swiper-container", ".swiper" } },
    { name = "Lottie", cat = "js", js = { "lottie", "bodymovin" } },
    { name = "Socket.IO", cat = "js", js = { "io.Socket", "io" }, scripts = { "socket%.io" } },
    { name = "core-js", cat = "js", js = { "__core-js_shared__" } },
    { name = "webpack", cat = "js", js = { "webpackChunk", "webpackJsonp", "__webpack_require__" }, html = { "webpackJsonp", "webpackChunk" } },
    { name = "Vite", cat = "js", scripts = { "/@vite/", "/assets/index%-[%w%-]+%.js" }, dom = { "script[type=module][src*='/assets/']" } },
    { name = "RequireJS", cat = "js", js = { "requirejs", "define.amd" } },
    { name = "PWA (Service Worker)", cat = "pwa", dom = { "link[rel=manifest]" }, js = { "navigator.serviceWorker.controller" } },
    -- ===== UI 框架 =====
    { name = "Bootstrap", cat = "ui", js = { "bootstrap" }, dom = { ".container-fluid .navbar", "link[href*='bootstrap']" }, html = { "bootstrap[%.%-]?[%d%.]*%.min%.css", "class=\"[^\"]*col%-md%-" }, version = { js = "bootstrap.Tooltip.VERSION" } },
    { name = "Tailwind CSS", cat = "ui", html = { "class=\"[^\"]*%f[%w%-]md:", "class=\"[^\"]*%f[%w%-]hover:", "%-%-tw%-" } },
    { name = "Material UI", cat = "ui", dom = { "[class*='MuiButton']", "[class*='MuiBox']", ".MuiTypography-root" }, implies = { "React" } },
    { name = "Ant Design", cat = "ui", dom = { ".ant-btn", ".ant-layout", "[class^='ant-']" }, js = { "antd" }, implies = { "React" } },
    { name = "Element UI / Element Plus", cat = "ui", dom = { ".el-button", ".el-container", "[class^='el-']" }, js = { "ELEMENT" }, implies = { "Vue.js" } },
    { name = "Vuetify", cat = "ui", dom = { ".v-application", ".v-btn" }, implies = { "Vue.js" } },
    { name = "Chakra UI", cat = "ui", dom = { "[class*='chakra-']" }, implies = { "React" } },
    { name = "Bulma", cat = "ui", dom = { ".hero.is-primary", "link[href*='bulma']" }, html = { "bulma%.min%.css" } },
    { name = "Font Awesome", cat = "font", dom = { ".fa,.fas,.fab,.far", "link[href*='font-awesome']", "link[href*='fontawesome']" }, scripts = { "fontawesome" } },
    { name = "Google Fonts", cat = "font", dom = { "link[href*='fonts.googleapis.com']" } },
    { name = "Radix UI", cat = "ui", dom = { "[data-radix-popper-content-wrapper]", "[data-radix-collection-item]" } },
    { name = "shadcn/ui", cat = "ui", dom = { "[cmdk-root]", ".sr-only+[data-state]" } },
    -- ===== CMS / 博客 / 电商 =====
    { name = "WordPress", cat = "cms", meta = { generator = "WordPress" }, scripts = { "/wp%-includes/", "/wp%-content/" }, html = { "/wp%-content/", "/wp%-includes/" }, implies = { "PHP", "MySQL" }, version = { meta = "generator", re = "WordPress ([%d%.]+)" } },
    { name = "WooCommerce", cat = "ecommerce", meta = { generator = "WooCommerce" }, dom = { ".woocommerce", "body.woocommerce-page" }, scripts = { "/plugins/woocommerce/" }, implies = { "WordPress" } },
    { name = "Elementor", cat = "cms", dom = { ".elementor", "[data-elementor-type]" }, scripts = { "/plugins/elementor/" }, implies = { "WordPress" } },
    { name = "Yoast SEO", cat = "cms", html = { "This site is optimized with the Yoast SEO", "yoast%-schema%-graph" }, implies = { "WordPress" } },
    { name = "Drupal", cat = "cms", meta = { generator = "Drupal" }, js = { "Drupal" }, headers = { ["x-generator"] = "Drupal", ["x-drupal-cache"] = "." }, scripts = { "/sites/default/files/" }, implies = { "PHP" } },
    { name = "Joomla", cat = "cms", meta = { generator = "Joomla" }, scripts = { "/media/jui/", "/media/system/js/" }, implies = { "PHP" } },
    { name = "Typecho", cat = "blog", meta = { generator = "Typecho" }, implies = { "PHP" } },
    { name = "Ghost", cat = "blog", meta = { generator = "Ghost" }, scripts = { "/public/ghost%-sdk", "ghost/api" }, implies = { "Node.js" } },
    { name = "Hexo", cat = "ssg", meta = { generator = "Hexo" } },
    { name = "Hugo", cat = "ssg", meta = { generator = "Hugo" } },
    { name = "Jekyll", cat = "ssg", meta = { generator = "Jekyll" } },
    { name = "VuePress", cat = "ssg", meta = { generator = "VuePress" }, dom = { "#app .theme-container" }, implies = { "Vue.js" } },
    { name = "VitePress", cat = "ssg", dom = { ".VPNav", ".vp-doc" }, implies = { "Vue.js", "Vite" } },
    { name = "Docusaurus", cat = "ssg", meta = { generator = "Docusaurus" }, dom = { "#__docusaurus" }, implies = { "React" } },
    { name = "MkDocs", cat = "ssg", meta = { generator = "mkdocs" }, dom = { ".md-header", "link[href*='mkdocs']" } },
    { name = "Sphinx", cat = "ssg", meta = { generator = "Sphinx" }, dom = { "link[href*='_static/pygments.css']" } },
    { name = "GitBook", cat = "ssg", meta = { generator = "GitBook" }, dom = { ".gitbook-root" } },
    { name = "Notion", cat = "cms", dom = { ".notion-page-content", ".notion-app-inner" } },
    { name = "Squarespace", cat = "cms", js = { "Static.SQUARESPACE_CONTEXT" }, scripts = { "squarespace%.com" } },
    { name = "Wix", cat = "cms", meta = { generator = "Wix%.com" }, js = { "wixBiSession" }, scripts = { "static%.parastorage%.com" } },
    { name = "Webflow", cat = "cms", meta = { generator = "Webflow" }, dom = { "html[data-wf-site]" }, scripts = { "webflow%.js" } },
    { name = "Framer", cat = "cms", meta = { generator = "Framer" }, dom = { "[data-framer-name]" } },
    { name = "HubSpot CMS", cat = "cms", meta = { generator = "HubSpot" }, scripts = { "js%.hs%-scripts%.com", "js%.hsforms%.net" } },
    { name = "Shopify", cat = "ecommerce", js = { "Shopify" }, scripts = { "cdn%.shopify%.com" }, headers = { ["x-shopify-stage"] = ".", ["x-shopid"] = "." }, implies = { "Ruby on Rails" } },
    { name = "Magento", cat = "ecommerce", js = { "Mage", "requirejs.s.contexts._.config.paths.mage" }, dom = { "[data-mage-init]" }, scripts = { "/static/version%d+/frontend/", "mage/" }, implies = { "PHP", "MySQL" } },
    { name = "PrestaShop", cat = "ecommerce", meta = { generator = "PrestaShop" }, js = { "prestashop" }, implies = { "PHP" } },
    { name = "OpenCart", cat = "ecommerce", scripts = { "catalog/view/javascript/" }, html = { "index%.php%?route=" }, implies = { "PHP" } },
    { name = "BigCommerce", cat = "ecommerce", scripts = { "cdn%d*%.bigcommerce%.com" }, dom = { "link[href*='bigcommerce.com']" } },
    { name = "Salesforce Commerce Cloud", cat = "ecommerce", scripts = { "demandware%.static" }, cookies = { "dwsid", "dwanonymous_" } },
    -- ===== 论坛 / Wiki / 课程 =====
    { name = "Discourse", cat = "forum", meta = { generator = "Discourse" }, dom = { "#main-outlet", "discourse-assets" }, implies = { "Ruby on Rails", "Ember.js" } },
    { name = "phpBB", cat = "forum", dom = { "body#phpbb" }, html = { "Powered by <a href=\"https://www%.phpbb%.com/\"" }, implies = { "PHP" } },
    { name = "Discuz!", cat = "forum", meta = { generator = "Discuz!" }, js = { "DISCUZCODE" }, scripts = { "/static/js/common%.js%?" }, implies = { "PHP" } },
    { name = "Flarum", cat = "forum", js = { "flarum" }, dom = { "#flarum-loading" } },
    { name = "NodeBB", cat = "forum", js = { "config.relative_path" }, dom = { "#content[data-template]" } },
    { name = "MediaWiki", cat = "wiki", meta = { generator = "MediaWiki" }, js = { "mw.config" }, dom = { "body.mediawiki" }, implies = { "PHP" } },
    { name = "Confluence", cat = "wiki", meta = { ["ajs-version-number"] = "." }, dom = { "#com-atlassian-confluence" } },
    { name = "Moodle", cat = "lms", js = { "M.cfg" }, dom = { "body#page-site-index", "link[href*='/theme/']" }, implies = { "PHP" } },
    -- ===== 服务端 / 语言 / 托管 =====
    { name = "nginx", cat = "server", headers = { server = "^nginx" } },
    { name = "Apache", cat = "server", headers = { server = "^Apache" } },
    { name = "Microsoft IIS", cat = "server", headers = { server = "^Microsoft%-IIS" }, implies = { "Windows Server" } },
    { name = "OpenResty", cat = "server", headers = { server = "^openresty" }, implies = { "nginx", "Lua" } },
    { name = "Tengine", cat = "server", headers = { server = "^Tengine" }, implies = { "nginx" } },
    { name = "LiteSpeed", cat = "server", headers = { server = "^LiteSpeed" } },
    { name = "Caddy", cat = "server", headers = { server = "^Caddy" } },
    { name = "Envoy", cat = "server", headers = { server = "^envoy", ["x-envoy-upstream-service-time"] = "." } },
    { name = "Gunicorn", cat = "server", headers = { server = "^gunicorn" }, implies = { "Python" } },
    { name = "uvicorn", cat = "server", headers = { server = "^uvicorn" }, implies = { "Python" } },
    { name = "Kestrel", cat = "server", headers = { server = "^Kestrel" }, implies = { "ASP.NET Core" } },
    { name = "PHP", cat = "lang", headers = { ["x-powered-by"] = "PHP", ["set-cookie"] = "PHPSESSID" }, cookies = { "PHPSESSID" }, url = { "%.php[%?$]" }, version = { header = "x-powered-by", re = "PHP/([%d%.]+)" } },
    { name = "ASP.NET", cat = "framework", headers = { ["x-powered-by"] = "ASP%.NET", ["x-aspnet-version"] = "." }, cookies = { "ASP%.NET_SessionId", "%.AspNetCore%." }, dom = { "input[name=__VIEWSTATE]" }, url = { "%.aspx[%?$]" } },
    { name = "ASP.NET Core", cat = "framework", cookies = { "%.AspNetCore%." }, headers = { ["x-powered-by"] = "ASP%.NET Core" } },
    { name = "Express", cat = "framework", headers = { ["x-powered-by"] = "^Express" }, implies = { "Node.js" } },
    { name = "Node.js", cat = "lang" },
    { name = "Ruby on Rails", cat = "framework", headers = { ["x-powered-by"] = "Phusion Passenger", ["x-runtime"] = "^[%d%.]+$" }, cookies = { "_rails_session", "_session_id" }, dom = { "meta[name=csrf-param][content=authenticity_token]" }, implies = { "Ruby" } },
    { name = "Ruby", cat = "lang" },
    { name = "Django", cat = "framework", cookies = { "^csrftoken$", "^django_language$", "^sessionid$" }, dom = { "input[name=csrfmiddlewaretoken]" }, implies = { "Python" } },
    { name = "Flask", cat = "framework", headers = { server = "Werkzeug" }, implies = { "Python" } },
    { name = "FastAPI", cat = "framework", url = { "/docs$", "/openapi%.json" }, dom = { "link[href*='swagger-ui']" }, implies = { "Python" } },
    { name = "Python", cat = "lang" },
    { name = "Laravel", cat = "framework", cookies = { "^laravel_session$", "^XSRF%-TOKEN$" }, dom = { "meta[name=csrf-token]" }, implies = { "PHP" } },
    { name = "Symfony", cat = "framework", cookies = { "^sf_redirect$" }, headers = { ["x-debug-token"] = "." }, dom = { ".sf-toolbar" }, implies = { "PHP" } },
    { name = "ThinkPHP", cat = "framework", headers = { ["x-powered-by"] = "ThinkPHP" }, cookies = { "^think_" }, implies = { "PHP" } },
    { name = "Spring", cat = "framework", cookies = { "^JSESSIONID$" }, headers = { ["x-application-context"] = "." }, implies = { "Java" } },
    { name = "Java", cat = "lang", cookies = { "^JSESSIONID$" }, url = { "%.jsp[%?$]", "%.do[%?$]", "%.action[%?$]" } },
    { name = "Go", cat = "lang", headers = { ["x-powered-by"] = "^Go", server = "^Go%-http" } },
    { name = "Lua", cat = "lang" },
    { name = "MySQL", cat = "misc" },
    { name = "Windows Server", cat = "misc" },
    { name = "Vercel", cat = "hosting", headers = { server = "^Vercel", ["x-vercel-id"] = ".", ["x-vercel-cache"] = "." } },
    { name = "Netlify", cat = "hosting", headers = { server = "^Netlify", ["x-nf-request-id"] = "." } },
    { name = "Cloudflare Pages", cat = "hosting", headers = { ["cf-ray"] = ".", ["x-cloudflare-pages"] = "." } },
    { name = "GitHub Pages", cat = "hosting", headers = { server = "^GitHub%.com", ["x-github-request-id"] = "." } },
    { name = "Heroku", cat = "hosting", headers = { via = "vegur" } },
    { name = "Firebase Hosting", cat = "hosting", headers = { ["x-served-by"] = "firebase" }, scripts = { "/__/firebase/" } },
    { name = "AWS", cat = "hosting", headers = { ["x-amz-cf-id"] = ".", ["x-amz-request-id"] = ".", server = "^AmazonS3" } },
    { name = "Amazon CloudFront", cat = "cdn", headers = { via = "CloudFront", ["x-amz-cf-pop"] = "." } },
    { name = "Cloudflare", cat = "cdn", headers = { server = "^cloudflare", ["cf-ray"] = "." }, cookies = { "__cfduid", "__cf_bm", "cf_clearance" }, scripts = { "cdn%-cgi/", "static%.cloudflareinsights%.com" } },
    { name = "Fastly", cat = "cdn", headers = { ["x-served-by"] = "^cache%-", ["x-fastly-request-id"] = "." } },
    { name = "Akamai", cat = "cdn", headers = { ["x-akamai-transformed"] = ".", server = "AkamaiGHost" }, cookies = { "^ak_bmsc$", "^bm_sz$" } },
    { name = "阿里云 CDN", cat = "cdn", headers = { ["x-swift-cachetime"] = ".", server = "^Tengine", ["eagleid"] = "." } },
    { name = "腾讯云 CDN", cat = "cdn", headers = { ["x-nws-log-uuid"] = ".", server = "^NWS", ["x-cache-lookup"] = "." } },
    { name = "百度云加速", cat = "cdn", headers = { server = "^yunjiasu" } },
    { name = "又拍云", cat = "cdn", headers = { server = "^marco", ["x-upyun-"] = "." } },
    { name = "jsDelivr", cat = "cdn", scripts = { "cdn%.jsdelivr%.net" } },
    { name = "unpkg", cat = "cdn", scripts = { "unpkg%.com" } },
    { name = "cdnjs", cat = "cdn", scripts = { "cdnjs%.cloudflare%.com" } },
    { name = "BootCDN", cat = "cdn", scripts = { "cdn%.bootcdn%.net", "cdn%.bootcss%.com" } },
    { name = "Staticfile CDN", cat = "cdn", scripts = { "cdn%.staticfile%.org", "cdn%.staticfile%.net" } },
    -- ===== 统计 / 广告 / 标签 / 营销 =====
    { name = "Google Analytics", cat = "analytics", js = { "ga", "gaGlobal", "GoogleAnalyticsObject" }, scripts = { "google%-analytics%.com/analytics%.js", "google%-analytics%.com/ga%.js", "googletagmanager%.com/gtag/js" }, cookies = { "^_ga$", "^_gid$" } },
    { name = "Google Analytics 4", cat = "analytics", scripts = { "googletagmanager%.com/gtag/js%?id=G%-" }, html = { "gtag%('config', ?'G%-" }, cookies = { "^_ga_" } },
    { name = "Google Tag Manager", cat = "tag", js = { "google_tag_manager" }, scripts = { "googletagmanager%.com/gtm%.js" }, html = { "googletagmanager%.com/gtm%.js" } },
    { name = "Google AdSense", cat = "ads", js = { "adsbygoogle" }, scripts = { "pagead2%.googlesyndication%.com" } },
    { name = "Google Ads", cat = "ads", scripts = { "googleadservices%.com", "googleads%.g%.doubleclick%.net" } },
    { name = "Google Publisher Tag", cat = "ads", js = { "googletag" }, scripts = { "securepubads%.g%.doubleclick%.net/tag/js/gpt%.js" } },
    { name = "Facebook Pixel", cat = "analytics", js = { "fbq" }, scripts = { "connect%.facebook%.net/[%w_]+/fbevents%.js" }, cookies = { "^_fbp$" } },
    { name = "Hotjar", cat = "analytics", js = { "hj", "_hjSettings" }, scripts = { "static%.hotjar%.com" } },
    { name = "Microsoft Clarity", cat = "analytics", js = { "clarity" }, scripts = { "clarity%.ms/tag/" }, cookies = { "^_clck$" } },
    { name = "Mixpanel", cat = "analytics", js = { "mixpanel" }, scripts = { "cdn%.mxpnl%.com" } },
    { name = "Segment", cat = "analytics", js = { "analytics.SNIPPET_VERSION" }, scripts = { "cdn%.segment%.com" } },
    { name = "Amplitude", cat = "analytics", js = { "amplitude" }, scripts = { "cdn%.amplitude%.com" } },
    { name = "PostHog", cat = "analytics", js = { "posthog" }, scripts = { "posthog%.com/static/", "/static/array%.js" } },
    { name = "Plausible", cat = "analytics", js = { "plausible" }, scripts = { "plausible%.io/js/" } },
    { name = "Matomo", cat = "analytics", js = { "Piwik", "Matomo", "_paq" }, scripts = { "matomo%.js", "piwik%.js" } },
    { name = "Umami", cat = "analytics", js = { "umami" }, dom = { "script[data-website-id]" } },
    { name = "百度统计", cat = "analytics", js = { "_hmt" }, scripts = { "hm%.baidu%.com/hm%.js" }, cookies = { "^Hm_lvt_" } },
    { name = "友盟 / CNZZ", cat = "analytics", js = { "_czc" }, scripts = { "cnzz%.com", "umeng%.com" } },
    { name = "51.la", cat = "analytics", js = { "LA" }, scripts = { "js%.users%.51%.la", "sdk%.51%.la" } },
    { name = "GrowingIO", cat = "analytics", js = { "gio" }, scripts = { "assets%.giocdn%.com" } },
    { name = "神策", cat = "analytics", js = { "sensorsDataAnalytic201505", "sensors" }, scripts = { "sensorsdata" } },
    { name = "Sentry", cat = "security", js = { "Sentry", "__SENTRY__" }, scripts = { "browser%.sentry%-cdn%.com" } },
    { name = "New Relic", cat = "analytics", js = { "NREUM", "newrelic" }, scripts = { "js%-agent%.newrelic%.com" } },
    { name = "Datadog RUM", cat = "analytics", js = { "DD_RUM" }, scripts = { "datadoghq%-browser%-agent%.com" } },
    { name = "Optimizely", cat = "ab", js = { "optimizely" }, scripts = { "cdn%.optimizely%.com" } },
    { name = "VWO", cat = "ab", js = { "_vwo_code", "VWO" }, scripts = { "dev%.visualwebsiteoptimizer%.com" } },
    { name = "HubSpot", cat = "marketing", js = { "_hsq", "HubSpotConversations" }, scripts = { "js%.hs%-analytics%.net", "js%.hs%-scripts%.com" }, cookies = { "^hubspotutk$" } },
    { name = "Mailchimp", cat = "marketing", scripts = { "chimpstatic%.com", "list%-manage%.com" } },
    { name = "OneTrust", cat = "security", js = { "OneTrust", "OptanonWrapper" }, scripts = { "cdn%.cookielaw%.org" }, cookies = { "^OptanonConsent$" } },
    { name = "Cookiebot", cat = "security", js = { "Cookiebot" }, scripts = { "consent%.cookiebot%.com" } },
    -- ===== 客服 / 验证码 / 支付 / 地图 / 视频 / 搜索 =====
    { name = "Intercom", cat = "chat", js = { "Intercom" }, scripts = { "widget%.intercom%.io" } },
    { name = "Zendesk", cat = "chat", js = { "zE", "zEmbed" }, scripts = { "static%.zdassets%.com" } },
    { name = "Crisp", cat = "chat", js = { "$crisp" }, scripts = { "client%.crisp%.chat" } },
    { name = "Tawk.to", cat = "chat", js = { "Tawk_API" }, scripts = { "embed%.tawk%.to" } },
    { name = "LiveChat", cat = "chat", js = { "LiveChatWidget", "__lc" }, scripts = { "cdn%.livechatinc%.com" } },
    { name = "Drift", cat = "chat", js = { "drift" }, scripts = { "js%.driftt%.com" } },
    { name = "美洽", cat = "chat", js = { "_MEIQIA" }, scripts = { "static%.meiqia%.com" } },
    { name = "reCAPTCHA", cat = "captcha", js = { "grecaptcha" }, scripts = { "google%.com/recaptcha", "recaptcha%.net/recaptcha" }, dom = { ".g-recaptcha" } },
    { name = "hCaptcha", cat = "captcha", js = { "hcaptcha" }, scripts = { "js%.hcaptcha%.com" }, dom = { ".h-captcha" } },
    { name = "Cloudflare Turnstile", cat = "captcha", js = { "turnstile" }, scripts = { "challenges%.cloudflare%.com/turnstile" }, dom = { ".cf-turnstile" } },
    { name = "极验", cat = "captcha", js = { "initGeetest", "initGeetest4" }, scripts = { "static%.geetest%.com" } },
    { name = "Stripe", cat = "payment", js = { "Stripe" }, scripts = { "js%.stripe%.com" } },
    { name = "PayPal", cat = "payment", js = { "paypal" }, scripts = { "paypal%.com/sdk/js", "paypalobjects%.com" } },
    { name = "Braintree", cat = "payment", js = { "braintree" }, scripts = { "js%.braintreegateway%.com" } },
    { name = "Google Maps", cat = "map", js = { "google.maps" }, scripts = { "maps%.googleapis%.com/maps/api", "maps%.google%.com/maps" } },
    { name = "Mapbox", cat = "map", js = { "mapboxgl" }, scripts = { "api%.mapbox%.com/mapbox%-gl%-js" } },
    { name = "Leaflet", cat = "map", js = { "L.map", "L.Marker" }, dom = { ".leaflet-container" } },
    { name = "高德地图", cat = "map", js = { "AMap" }, scripts = { "webapi%.amap%.com" } },
    { name = "百度地图", cat = "map", js = { "BMap", "BMapGL" }, scripts = { "api%.map%.baidu%.com" } },
    { name = "YouTube Embed", cat = "video", dom = { "iframe[src*='youtube.com/embed']", "iframe[src*='youtube-nocookie.com']" } },
    { name = "Vimeo", cat = "video", dom = { "iframe[src*='player.vimeo.com']" }, scripts = { "player%.vimeo%.com/api/player%.js" } },
    { name = "Video.js", cat = "video", js = { "videojs" }, dom = { ".video-js" } },
    { name = "Plyr", cat = "video", js = { "Plyr" }, dom = { ".plyr" } },
    { name = "DPlayer", cat = "video", js = { "DPlayer" }, dom = { ".dplayer" } },
    { name = "hls.js", cat = "video", js = { "Hls" } },
    { name = "Bilibili Embed", cat = "video", dom = { "iframe[src*='player.bilibili.com']" } },
    { name = "Algolia", cat = "search", js = { "algoliasearch", "instantsearch" }, scripts = { "cdn%.jsdelivr%.net/npm/algoliasearch", "algolia%.net" }, dom = { ".ais-InstantSearch", "#docsearch" } },
    { name = "Elasticsearch / Kibana", cat = "search", dom = { "kbn-injected-metadata", "#kibana-body" } },
    { name = "Meilisearch", cat = "search", js = { "MeiliSearch", "meilisearch" } },
    -- ===== 其它常见 =====
    { name = "Open Graph", cat = "misc", dom = { "meta[property^='og:']" } },
    { name = "Twitter Cards", cat = "misc", dom = { "meta[name^='twitter:']" } },
    { name = "Schema.org (JSON-LD)", cat = "misc", dom = { "script[type='application/ld+json']" } },
    { name = "AMP", cat = "misc", dom = { "html[amp]", "html[⚡]" }, scripts = { "cdn%.ampproject%.org" } },
    { name = "Disqus", cat = "misc", js = { "DISQUS" }, scripts = { "disqus%.com/embed%.js" } },
    { name = "Giscus", cat = "misc", scripts = { "giscus%.app/client%.js" } },
    { name = "Gitalk", cat = "misc", js = { "Gitalk" } },
    { name = "MathJax", cat = "misc", js = { "MathJax" }, scripts = { "mathjax" } },
    { name = "KaTeX", cat = "misc", js = { "katex" }, dom = { ".katex" } },
    { name = "highlight.js", cat = "misc", js = { "hljs" }, dom = { "pre code.hljs" } },
    { name = "Prism", cat = "misc", js = { "Prism" }, dom = { "pre[class*='language-']" } },
    { name = "Monaco Editor", cat = "misc", js = { "monaco" }, dom = { ".monaco-editor" } },
    { name = "CodeMirror", cat = "misc", js = { "CodeMirror" }, dom = { ".CodeMirror", ".cm-editor" } },
    { name = "TinyMCE", cat = "misc", js = { "tinymce" }, dom = { ".tox-tinymce" } },
    { name = "CKEditor", cat = "misc", js = { "CKEDITOR", "ClassicEditor" }, dom = { ".ck-editor" } },
    { name = "Quill", cat = "misc", js = { "Quill" }, dom = { ".ql-editor" } },
    { name = "Gravatar", cat = "misc", dom = { "img[src*='gravatar.com/avatar']" } },
    { name = "WordPress Jetpack", cat = "cms", scripts = { "/plugins/jetpack/", "stats%.wp%.com" }, implies = { "WordPress" } },
    { name = "Wordfence", cat = "security", scripts = { "/plugins/wordfence/" }, implies = { "WordPress" } },
    { name = "Varnish", cat = "cdn", headers = { ["x-varnish"] = ".", via = "varnish" } },
    { name = "Squid", cat = "cdn", headers = { ["x-squid-error"] = ".", via = "squid" } },
    { name = "HSTS", cat = "security", headers = { ["strict-transport-security"] = "." } },
    { name = "HTTP/3", cat = "misc", headers = { ["alt-svc"] = "h3" } },
    { name = "Docker Registry", cat = "misc", headers = { ["docker-distribution-api-version"] = "." } },
    { name = "Gitea", cat = "misc", meta = { keywords = "gitea" }, dom = { "body.page-home .gitea" }, js = { "config.appUrl" } },
    { name = "GitLab", cat = "misc", meta = { ["og:site_name"] = "GitLab" }, dom = { "body[data-page^='projects']", ".gl-" }, js = { "gon" } },
    { name = "Grafana", cat = "misc", js = { "grafanaBootData" }, dom = { "grafana-app" } },
    { name = "Jenkins", cat = "misc", headers = { ["x-jenkins"] = "." } },
    { name = "phpMyAdmin", cat = "misc", dom = { "#pma_navigation", "body.pma" }, cookies = { "^pma_" }, implies = { "PHP", "MySQL" } },
    { name = "Swagger UI", cat = "misc", dom = { "#swagger-ui", ".swagger-ui" } },
    { name = "Redoc", cat = "misc", dom = { "redoc" } },
    { name = "Umi", cat = "framework", js = { "g_umi" }, dom = { "#root .ant-pro-layout" }, implies = { "React" } },
    { name = "Taro", cat = "framework", js = { "__taroAppConfig" }, dom = { "taro-view-core" } },
    { name = "uni-app", cat = "framework", js = { "__uniConfig" }, dom = { "uni-app", "uni-page" }, implies = { "Vue.js" } },
    { name = "Layui", cat = "ui", js = { "layui" }, dom = { ".layui-layout" } },
    { name = "WeUI", cat = "ui", dom = { ".weui-cell", "[class^='weui-']" } },
    { name = "Vant", cat = "ui", dom = { ".van-button", "[class^='van-']" }, implies = { "Vue.js" } },
    { name = "Naive UI", cat = "ui", dom = { ".n-config-provider", ".n-button" }, implies = { "Vue.js" } },
    { name = "Arco Design", cat = "ui", dom = { ".arco-btn", "[class^='arco-']" } },
    { name = "TDesign", cat = "ui", dom = { ".t-button", "[class^='t-']" } },
    { name = "Semi Design", cat = "ui", dom = { "[class^='semi-']" }, implies = { "React" } },
    { name = "Bilibili Player", cat = "video", dom = { ".bpx-player-container" } },
}

return M
